### PR TITLE
Build 3.2.1

### PR DESCRIPTION
**Pull request by awokd**
https://github.com/QubesOS/qubes-issues/issues/3426

### CODE REVIEW

**Comment by awokd** [comment]
those TEMPLATE_ALIASes seemed to already be in place in example-configs/templates.conf:

  TEMPLATE_ALIAS += stretch:stretch+standard
  TEMPLATE_ALIAS += stretch+gnome:stretch+gnome+standard
  TEMPLATE_ALIAS += stretch+minimal:stretch+minimal+no-recommends

**Comment by marmarek** [comment]
But qubes-os-r3.2.conf should be sufficient for full build, without
additionally sourcing templates.conf.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by awokd** [comment]
Sorry, didn't know! In that case, should these also be added to qubes-os-r3.2.conf?

+TEMPLATE_LABEL += stretch:debian-9
+TEMPLATE_LABEL += stretch+standard:debian-9

**Comment by marmarek** [comment]
Yes, I've already done that.

**Comment by awokd** [comment]
Thanks, wanted to make sure so I'd get it right next time!

**Pull request merged**
