### PR TITLE
setup: support for adding pre-built packages repositories

### PR DESCRIPTION
**Pull request by fepitre**
QubesOS/qubes-issues#4788

### CODE REVIEW

**Comment by marmarek** [comment]
I think this new prompt logically should be just after asking for source repositories.

**Comment by fepitre** [comment]
Done :+1:

**Comment by marmarek** [comment]
It does not detect the current value if you run `./setup` again.

**Comment by fepitre** [comment]
Yes indeed, I assumed that it was generated from scratch. Few things to adapt then.

**Comment by marmarek** [comment]
Looks good now.

**Pull request merged**
