### PR TITLE
Allow plugins to manage 'packages' target

### PR DESCRIPTION
**Pull request by fepitre**
QubesOS/qubes-issues#5564

### CODE REVIEW

**Comment by fepitre** [comment]
This is a first attempt. Certainly to be improved.

**Comment by marmarek** [comment]
We have already primitive for checking if package is built, used in `make check-release-status` - besides checking for package existence, it also implicitly compare versions. See also how it's done in `scripts/auto-build`.

Adding extra stamp file is not a bad idea, but besides FORCE_BUILD, there needs to be some freshness check. Maybe it should contain commit id of what has been built? And then not only check for existence, but compare commit id.

Corner cases that needs some handling:
 - updating sources (make get-sources)
 - switching between branches (building `some-feature` branch, then switching back to `master` for example)
 - building with local changes not committed yet (I think it should effectively imply FORCE_BUILD)

Generally, incorrectly skipping the build is worse than building twice. It is always very frustrating to find your fixes don't work, because you've tested code without them at all.

**Comment by fepitre** [comment]
Thank you for your comment. I'll will work in this direction suggested.

**Comment by JarrahG** [comment]
This patch seems to be skipping some builds on first build. The main example I have is qubes-kernel-vm-support being skipped in linux-utils. 
```
-> Building linux-utils (rpm_spec/qubes-utils.spec) for fc31 dom0 (logfile: build-logs/linux-utils-dom0-fc31.log)
--> Done:
      qubes-src/linux-utils/pkgs/dom0-fc31/x86_64/python2-qubesimgconverter-4.1.3-1.fc31.x86_64.rpm
      qubes-src/linux-utils/pkgs/dom0-fc31/x86_64/python3-qubesimgconverter-4.1.3-1.fc31.x86_64.rpm
      qubes-src/linux-utils/pkgs/dom0-fc31/x86_64/qubes-utils-4.1.3-1.fc31.x86_64.rpm
      qubes-src/linux-utils/pkgs/dom0-fc31/x86_64/qubes-utils-debuginfo-4.1.3-1.fc31.x86_64.rpm
      qubes-src/linux-utils/pkgs/dom0-fc31/x86_64/qubes-utils-debugsource-4.1.3-1.fc31.x86_64.rpm
      qubes-src/linux-utils/pkgs/dom0-fc31/x86_64/qubes-utils-devel-4.1.3-1.fc31.x86_64.rpm
      qubes-src/linux-utils/pkgs/dom0-fc31/x86_64/qubes-utils-libs-4.1.3-1.fc31.x86_64.rpm
      qubes-src/linux-utils/pkgs/dom0-fc31/x86_64/qubes-utils-libs-debuginfo-4.1.3-1.fc31.x86_64.rpm
-> Skipping already built linux-utils (rpm_spec/qubes-kernel-vm-support.spec) for fc31 dom0
make[1]: Leaving directory '/home/user/qubes-builder'
git -C /home/user/qubes-builder/chroot-vm-fc30/home/user/qubes-src/linux-utils clean -f -d -X
/home/user/qubes-builder/scripts/create-archive /home/user/qubes-builder/chroot-vm-fc30/home/user/qubes-src/linux-utils qubes-utils-4.1.3.tar.gz
~/qubes-builder/chroot-vm-fc30/home/user/qubes-src/linux-utils ~/qubes-builder
~/qubes-builder
-> Building linux-utils (rpm_spec/qubes-utils.spec) for fc30 vm (logfile: build-logs/linux-utils-vm-fc30.log)
--> Done:
      qubes-src/linux-utils/pkgs/vm-fc30/x86_64/python2-qubesimgconverter-4.1.3-1.fc30.x86_64.rpm
      qubes-src/linux-utils/pkgs/vm-fc30/x86_64/python3-qubesimgconverter-4.1.3-1.fc30.x86_64.rpm
      qubes-src/linux-utils/pkgs/vm-fc30/x86_64/qubes-utils-4.1.3-1.fc30.x86_64.rpm
      qubes-src/linux-utils/pkgs/vm-fc30/x86_64/qubes-utils-debuginfo-4.1.3-1.fc30.x86_64.rpm
      qubes-src/linux-utils/pkgs/vm-fc30/x86_64/qubes-utils-debugsource-4.1.3-1.fc30.x86_64.rpm
      qubes-src/linux-utils/pkgs/vm-fc30/x86_64/qubes-utils-devel-4.1.3-1.fc30.x86_64.rpm
      qubes-src/linux-utils/pkgs/vm-fc30/x86_64/qubes-utils-libs-4.1.3-1.fc30.x86_64.rpm
      qubes-src/linux-utils/pkgs/vm-fc30/x86_64/qubes-utils-libs-debuginfo-4.1.3-1.fc30.x86_64.rpm
-> Skipping already built linux-utils (rpm_spec/qubes-kernel-vm-support.spec) for fc30 vm
```

**Comment by fepitre** [comment]
Yes because it's too dummy. For multiple rpm spec it does not work. In this case it would be better to replace component name by spec file name.

**Comment by fepitre** [comment]
We need to find a better naming for OUTPUT and SOURCES. Also in https://github.com/QubesOS/qubes-builder-rpm/pull/64. BTW, for debian I need to check exactly how devel increment is done.

**Pull request closed without merging**
