### PR TITLE
scripts/build: no need to mount builder repo dir anymore

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Comment by fepitre** [comment]
PipelineRefresh

**Comment by fepitre** [comment]
PipelineRefresh

**Comment by fepitre** [comment]
PipelineRefresh

**Comment by fepitre** [comment]
PipelineRefresh

**Comment by fepitre** [comment]
PipelineRefresh

**Comment by fepitre** [comment]
PipelineRefresh

**Comment by fepitre** [comment]
@marmarek build is fine.

**Comment by marmarek** [comment]
PipelineRefresh

**Review by marmarek — APPROVED** [review]

**Pull request merged**
