### PR TITLE
install-deps: use createrepo_c instead of createrepo

### PR DESCRIPTION
**Pull request by fepitre**
If there is any reason to not use ```createrepo_c``` instead of ```createrepo```, close the PR but in Fedora 30+, it leads to always downgrading the package ```createrepo_c``` and any update will re-update it...

### CODE REVIEW

**Comment by fepitre** [comment]
We need to adjust in other components call to ```createrepo``` like in ```update-local-repos.sh```.

**Comment by fepitre** [comment]
@marmarek: I added something related to PKG_MANGER? does it do the job?

**Comment by marmarek** [comment]
Can you add a comment why you did it this way?

**Comment by fepitre** [comment]
I used the same trick for knowing what is the host distro for the builder in order to properly determine what are the related dependencies. In this case, the choice between ```createrepo``` and ```createrepo_c```.

**Comment by marmarek** [comment]
I know this, but please add a comment, as otherwise it looks weird for anyone else.

**Comment by fepitre** [comment]
Oh ok, comment in the Makefile, I thought it was to remind you the problem :)

**Pull request merged**
