### PR TITLE
Add desktop-linux-common component

### PR DESCRIPTION
**Pull request by jpouellet**
Would be required if we want a separate https://github.com/jpouellet/qubes-desktop-linux-common

### CODE REVIEW

**Comment by jpouellet** [comment]
See https://github.com/QubesOS/qubes-issues/issues/2735

**Comment by marmarek** [comment]
I'm not sure about having this change in 3.2 (a stable release). But even if we decide to do so, we need to make sure the dependency will be correctly set for smooth transition. This for example means desktop-linux-common must `Conflicts: qubes-core-admin-linux < <version-where-qvm-xkill-was-removed>`.

**Comment by jpouellet** [comment]
Not making changes like this to 3.2 sounds reasonable to me.

But regardless of time-frame, do you think this (https://github.com/QubesOS/qubes-issues/issues/2735) is a desired end state?

**Comment by marmarek** [comment]
Yes, I like this approach.

**Comment by marmarek** [comment]
Added to qubes-os-master.conf only.

**Pull request closed without merging**
